### ISSUE TITLE
keeping, rewording, or drop H1

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-deleg/draft-ietf-deleg-requirements#11]
Current H1 :  DELEG must not disrupt the existing registration model of domains.  Reservation of a name at a registry will still use the relevant registrar system to indicate the authorized registrant.

**Comment by vttale** [comment]
I think H1 is good as-is.  It broadly and yet succinctly covers that different ecosystems of parents (registries) and children (registrants) exist and they we do not seek to change the relationship between them.   Their existing framework for determining who has what names can continue as-is, independent from this protocol work.

**Comment by wessels** [comment]
My sense from the interim meeting was rough consensus to keep H1 as is.

**Comment by moonshiner** [comment]
Streamlined this and looks clearer
