### ISSUE TITLE
Not naming the WG in the draft

### ISSUE THREAD

**Issue by paulehoffman** [ietf-wg-deleg/draft-ietf-deleg-requirements#4]
The draft says "However, the working group should strive to test any proposed mechanism against a wide range of legacy software and come to a consensus as to what constitutes adherence to this requirement." That's not appropriate wording for the eventual RFC, even as as soft requirement. This would be better as some wording before the beginning of 3.1, and not put it on the WG but instead on the community.

**Comment by moonshiner** [comment]
this makes sense.  we will wordsmith something

**Comment by moonshiner** [comment]
I replaced "working group" with "DNS community" for now
